### ISSUE TITLE
「北风卷地白草折，胡天八月即飞雪」3qJDPV/A0rlp。

### ISSUE THREAD

**Issue by Zoro916** [Zoro916/enn-design-doc#2]
「桃花坞里桃花庵，桃花庵里桃花仙。桃花仙人种桃树，又折花枝当酒钱。酒醒只在花前坐，酒醉还须花下眠。花前花后日复日，酒醉酒醒年复年。不愿鞠躬车马前，但愿老死花酒间。车尘马足贵者趣，酒盏花枝贫者缘。若将富贵比贫贱，一在平地一在天。若将贫贱比车马，他得驱驰我得闲」3i1rwo/1Q45nI。

**Comment by Zoro916** [comment]
「醉里挑灯看剑」7mbuJ/4VmymT。

**Comment by jx-web** [comment]
「柳丝长」2dq2Kf/4W0Shg。

**Comment by Zoro916** [comment]
> 柳丝长

「菡萏香销翠叶残，西风愁起绿波间。还与韶光共憔悴，不堪看。细雨梦回鸡塞远，小楼吹彻玉笙寒。多少泪珠何限恨」ZB1If/2VjazA。

**Comment by jx-web** [comment]
「云一緺，玉一梭，淡淡衫儿薄薄罗，轻颦双黛螺。秋风多，雨相和，帘外芭蕉三两窠」b8GVd/2u3p2W。

**Comment by Zoro916** [comment]
「阑干十二独凭春，晴碧远连云。千里万里，二月三月，行色苦愁人。谢家池上，江淹浦畔，吟魄与离魂」3lbip9/MHg4e。

**Comment by Zoro916** [comment]
> 云一緺，玉一梭，淡淡衫儿薄薄罗，轻颦双黛螺。秋风多，雨相和，帘外芭蕉三两窠

「阑干十二独凭春」2WQIgp/PgBgu。

**Comment by jx-web** [comment]
「一钩初月临妆镜，蝉鬓凤钗慵不整」13p3Ah/1650g4。

**Comment by Zoro916** [comment]
我不能送你。。

**Comment by Zoro916** [comment]
「世人都晓神仙好，惟有功名忘不了」BrHn/1DfWxB。

**Comment by Zoro916** [comment]
> 「一钩初月临妆镜，蝉鬓凤钗慵不整」13p3Ah/1650g4。

「醉里挑灯看剑，梦回吹角连营」2hVPih/3fOLPj。
